### PR TITLE
Filesystem manifest consumer

### LINKED ISSUE #104: Consumer for filesystem carriage mechanism
Task for #50 
Create the consumer part for the filesystem carriage mechanism, along with the ability to simulate a the playout of the files like :

```
Document sequence number 1 loaded, availability time 15:00:00.
ISDs:
15:00:00-15:00:05 - no text presented
15:00:05-15:00:15 - "first document"
```

However note that this "simulation" part is likely to be broken in smaller issue as it nearly implements the logic behind a presenter node. Moreover it could make use of #89 so maybe it is wiser to wait on this one for now.

### PR DESCRIPTION
**Pull request by gilbrechbuhler**
This is the consumer part for the FileSystem carriage mechanism. You can test it easily by first creating a folder with a manifest using the producer : 
`ebu-simple-producer --folder-export test_output` 
and then calling the consumer and giving him the manifest file : 
`ebu-simple-consumer -m test_output/manifest_testSeq.txt`. 
You will see that every document is correctly read.

There is also a `tail -f` like option : with an existing test_output folder and an existing manifest in it, launch the consumer like before but add the `-f` option : 
`ebu-simple-consumer -m test_output/manifest_testSeq.txt -f`, 
then launch the producer on the same folder again to add new files and new lines to the manifest : `ebu-simple-producer --folder-export test_output` 
and you will see the consumer log every new line.

fixes #104 #50 #64  #65

### CODE REVIEW

**Comment by nigelmegitt** [comment]
I can't get the consumer to work:

```shell
$ ebu-simple-consumer -m test_export1/
[INFO] (2016-07-28 09:37:03,735) in ebu_simple_consumer - This is a Simple Consumer example
Traceback (most recent call last):
  File "/Users/megitn02/Code/ebu/ebu-tt-live-toolkit/venv/bin/ebu-simple-consumer", line 9, in <module>
    load_entry_point('ebu-tt-live', 'console_scripts', 'ebu-simple-consumer')()
  File "/Users/megitn02/Code/ebu/ebu-tt-live-toolkit/ebu_tt_live/scripts/ebu_simple_consumer.py", line 41, in main
    fs_reader = FilesystemReader(manifest_path, consumer_impl, do_tail)
  File "/Users/megitn02/Code/ebu/ebu-tt-live-toolkit/ebu_tt_live/carriage/filesystem.py", line 152, in __init__
    with open(manifest_path, 'r') as manifest:
IOError: [Errno 21] Is a directory: 'test_export1/'
```

This is after running ebu-simple-producer, which seems to have worked fine.

**Comment by nigelmegitt** [comment]
Sorry me being silly. Once I put the manifest file in this works nicely.

**Comment by nigelmegitt** [comment]
Very happy with this indeed!

**Comment by nigelmegitt** [comment]
Not sure if it's quick and easy to write tests to cover the additional code - I'm not concerned by it particularly. Will merge by end of day today if no other comments.

**Comment by gilbrechbuhler** [comment]
Which additional node ? I use the `SimpleConsumer` node that already existed. If you mean the `ebu-simple-consumer` script, as it is a script to demonstrate the components I am not sure it really needs tests.

**Comment by nigelmegitt** [comment]
Node? I meant the additional **code** that's not tested and that results in the coverage drop, such as the line that makes the directory, as highlighted at https://coveralls.io/builds/7198990/source?filename=ebu_tt_live%2Fcarriage%2Ffilesystem.py or the reference clock setter/getter at https://coveralls.io/builds/7198990/source?filename=ebu_tt_live%2Fnode%2Fconsumer.py for example.

**Comment by gilbrechbuhler** [comment]
Sorry, I misread your message... Testing getters and setters is not necessary in general unless they have some specific behaviour. The parts not tested in the first link are calls to python function standard lib functions, I don't think it is necessary for now. Maybe to up the coverage percentage in the future.

**Comment by nigelmegitt** [comment]
Okay, that's not a blocker for us. I'm going to merge this now.

**Pull request merged**
