### PR TITLE
Bdd/smpte datatype

### PR DESCRIPTION
**Pull request by EyalLavi**

### CODE REVIEW

**Comment by EyalLavi** [comment]
As you prefer. I realised this but thought it would be better to keep it separate for the workflow/blame trail.

**Comment by kozmaz87** [comment]
You know you can blame by line in git right?

**Comment by gilbrechbuhler** [comment]
The only problem by doing a new features file is that it needs to be loaded in the test file to be executed and it may be a bit confusing to test clock and media in the same file but not smpte. Other opinions ?

**Comment by kozmaz87** [comment]
Afaik the test file can load multiple features right?

**Comment by gilbrechbuhler** [comment]
The template needs to be updated to be used with smpte apparently, I'm on it. Tests were not running as the new feature was not loaded anywhere.

**Comment by EyalLavi** [comment]
I can merge, it's easy enough. I'll work on the existing feature file now for R55 R56 R58 R59

**Comment by kozmaz87** [comment]
@EyalLavi awesome stuff that you link the feature files back in the conformance document. Good idea

**Comment by EyalLavi** [comment]
Thanks but the credit goes to Gil!

**Comment by nigelmegitt** [comment]
So does this PR need more work or is it ready for review?

**Comment by EyalLavi** [comment]
Based on Gil's comments, I'm moving all timebase format tests to the original file, so both PR155 and PR156 will be redundant.

**Comment by nigelmegitt** [comment]
Closing PR155 and PR156, leaving the branches in place.

**Pull request closed without merging**
