### PR TITLE
Bdd/sequence identical timing model

### LINKED ISSUE #183: Test R11

### PR DESCRIPTION
**Pull request by gilbrechbuhler**
Test for R11 : Every document in a sequence shall have an identical timing model as defined by using the same values for the `ttp:timeBase` and `ttp:clockMode` attributes. (Note issue to add `frameRate`, `frameRateMultiplier` and `dropMode` to this attribute set)

Fix #183

### CODE REVIEW

**Comment by gilbrechbuhler** [comment]
I will actually close this one for now. I skip the invalid tests because the code does not check anything else than the sequence identifier for now, but adding timebase and related attributes checks is not hard, I will do that and reopen it. Maybe only SMPTE will be a problem here, at worst I just skip SMPTE tests.

**Comment by gilbrechbuhler** [comment]
it is the best I can do for now, SMPTE is not truly implemented. I skip all the tests except one because we only have media and clockMode=local clocks implemented. There is some work to do to have everything needed for those tests. I propose to add them and unskip them in the future when utc and gps clocks will have been implemented.

**Comment by nigelmegitt** [comment]
Not sure of the status of this - is more work going to happen on it now that we have utc clock?

**Comment by gilbrechbuhler** [comment]
Having utc clock would allow me to unskip some tests.

**Comment by nigelmegitt** [comment]
Looks good to me.

**Pull request merged**
