### PR TITLE
Coveralls integration

### PR DESCRIPTION
**Pull request by kozmaz87**

### CODE REVIEW

**Comment by gilbrechbuhler** [comment]
great :+1:

**Comment by nigelmegitt** [comment]
Seems nifty - just want to check if there are any adverse commercial/legal implications of using coveralls, since I'm new to it?

**Comment by kozmaz87** [comment]
opensource == free that is all I got from their licensing. If private there is a fee...

**Comment by nigelmegitt** [comment]
@frans-ebu if you're happy with this (or don't need to check it) we can merge.

**Comment by frans-ebu** [comment]
@nigelmegitt I am happy with this. I don't see a problem with it and it is not part of the code anyhow.

**Pull request merged**
