### PR TITLE
Existing tests reference spec conformance item

### PR DESCRIPTION
**Pull request by gilbrechbuhler**
Tests simply reference the R numbers they test from the `SPEC_CONFORMANCE.md` document.

### CODE REVIEW

**Comment by gilbrechbuhler** [comment]
fix #75

**Comment by frans-ebu** [comment]
Let's merge :)

**Comment by nigelmegitt** [comment]
It's showing has having conflicts since I merged #55 - @gilbrechbuhler please could you do a merge with master and resolve the conflicts?

**Comment by gilbrechbuhler** [comment]
Conflict resolved, sorry for the delay

**Comment by nigelmegitt** [comment]
Thanks! Merging...

**Pull request merged**
