### PR TITLE
fix timecountTimingType bug

### PR DESCRIPTION
**Pull request by gilbrechbuhler**
Okay I said I would open less merge requests, but this fix was so quick to write and does not interfere with any other PR.

Look at #67 for explanations.

@kozmaz87 do you agree with the fix ?

### CODE REVIEW

**Comment by gilbrechbuhler** [comment]
Ok so XML and XSD do not support ^ and $ in their regexes

**Comment by kozmaz87** [comment]
I'm happy with it.

**Comment by nigelmegitt** [comment]
Are there accompanying tests that verify this works? Now that you've found the fault scenario we should add it to tests to make sure it doesn't get reintroduced by some well meaning person later (someone like me who comes around and "tidies up" without realising I'm breaking it).

**Comment by frans-ebu** [comment]
Elegant solution. I'd say add an issue for the tests @nigelmegitt suggested and merge this one.

**Comment by nigelmegitt** [comment]
okay I'm happy to do that.

**Comment by nigelmegitt** [comment]
Issue is #69 as just referenced. Will merge...

**Comment by nigelmegitt** [comment]
Thank you @gilbrechbuhler - another great PR!

**Pull request merged**
