### PR TITLE
div elements (p and div) minOccurs=0

### LINKED ISSUE #138: XSD : Empty div element is not allowed

### PR DESCRIPTION
**Pull request by gilbrechbuhler**
Fixes #138

### CODE REVIEW

**Comment by nigelmegitt** [comment]
Looks good to me.

**Comment by nigelmegitt** [comment]
@kozmaz87 please could you have a look and check this isn't going to break any pyxb stuff. I don't see why it should/would, I'm just nervous about working on the foundations...

**Comment by nigelmegitt** [comment]
@kozmaz87 ping?

**Comment by kozmaz87** [comment]
nope this will not break anything. ACK

**Pull request merged**
