### PR TITLE
Gh pages index

### LINKED ISSUE #127: Create an index.html page for gh-pages
Create an EBU-styled home page for the project on the gh-pages branch with links to:

1. tech.ebu.ch
2. The automatically generated documentation
3. The github repository.

And with a description of the goals of the project and how it is being created, and a welcoming message for any potential contributors.

### PR DESCRIPTION
**Pull request by gilbrechbuhler**
Fix #127 hopefully. We will have to merge this in master and look at what happens with travis and the gh-pages branch to be sure it works. It should work. The index.html is basic for now, it can always be improved later.

### CODE REVIEW

**Comment by nigelmegitt** [comment]
So do I have to bravely merge this to find out if it works? This could be fun...

**Comment by gilbrechbuhler** [comment]
Well the worst that can happen is travis failing. There are no changes to the code at all, so I don't think it can break anything.

**Comment by gilbrechbuhler** [comment]
Wait ! It worked !
http://ebu.github.io/ebu-tt-live-toolkit/

**Comment by gilbrechbuhler** [comment]
I thought the gh-pages branch should regenerated only when a commit to master is made...

**Comment by frans-ebu** [comment]
That commit is from 1 hour ago?

**Comment by frans-ebu** [comment]
Then there was a Master commit, as well, was it included in that one?

**Comment by gilbrechbuhler** [comment]
Okay I just found someone saying that online : "I understand that when testing PR travis actually checks how it would be when merged to master and when testing a branch it just pulls that branch".

So travis locally merges the pull request in master to check that the merge would not break things, but this triggers a full build on travis' local master branch and hence, following the conditional it has in its configuration file he builds the gh-pages branch. Note this only happens on an opened pull request not if you simply push to branch that is not pull requested.

**Comment by nigelmegitt** [comment]
That's tantalising - does that post not lead to a solution also?

**Comment by gilbrechbuhler** [comment]
https://github.com/travis-ci/travis-ci/issues/1147

But I do not think it is a bug, it is clearly a feature to try to build the merged PR. I don't know if there is a solution for our documentation building problem.

**Comment by nigelmegitt** [comment]
Is there a way to put into the branch being built a file whose presence could be tested and used to decide whether to deploy on build or not? Not sure how we would block this from being actually overwritten in master...

**Comment by frans-ebu** [comment]
Great, that explains all. 

Solution in #146

**Comment by gilbrechbuhler** [comment]
Seems that your solution is working, the documentation was not uploaded to gh-pages on the last push on this PR.

**Comment by nigelmegitt** [comment]
OK this is looking good but very sparse - @frans-ebu do you want to make the index.html page a bit more corporate, or just add some basic description?

**Comment by frans-ebu** [comment]
Good idea, but not a prio for me.

**Comment by nigelmegitt** [comment]
OK I will try to edit the content at some point soon on this branch before merging.

**Comment by nigelmegitt** [comment]
Good enough for now...

**Pull request merged**
