### PR TITLE
Timebase semantic testing

### PR DESCRIPTION
**Pull request by gilbrechbuhler**
Tests that the times are accepted/rejected correctly depending on the timebase value. SMPTE is not handled yet as its implementation and usage are really likely to change in close futur.

Handles issue #7

### CODE REVIEW

**Comment by nigelmegitt** [comment]
Great, thanks Gil, I'll take a look...

**Comment by nigelmegitt** [comment]
This looks fine. Shouldn't some of the tests that are being skipped now be caught even by the pyxb binding's basic validation?

**Comment by gilbrechbuhler** [comment]
Indeed like 1.5x correctly raises an exception, I thought about it and forgot to take a look, maybe it is possible to skip just some examples, I'll take a look and comment back.

**Comment by gilbrechbuhler** [comment]
So commenting the scenario examples that don't work is the solution. However, as they are commented, they are not listed as skipped tests, they are just no taken into account at all. So the result about how many tests ran and how many were skipped becomes wrong.

What do you prefer ? Skipping the whole scenarios until all their members work (so the number of skipped tests is correct) or commenting the scenario examples that don't work (numver of skipped test is wrong) ?

**Comment by gilbrechbuhler** [comment]
maybe @kozmaz87 as an opinion about this too

**Comment by nigelmegitt** [comment]
This is fine right now but we have a choice: @gilbrechbuhler do you want to:

1. go ahead and add some more tests for `ttp:timeBase="smpte" ttp:markerMode="continuous"` following the EBU meeting on Tuesday? OR
2. merge this as is and start a new branch for smpte tests?

I don't have any semantics to test for `ttp:markerMode="discontinuous"` yet because I don't know what the spec will do with that, but for continuous see [gitlab issue 114](https://git.ebu.io/ebutt/ebutt-part-3/issues/114) where there is a requirement to test that the timing mode is the same across the whole sequence.

**Comment by gilbrechbuhler** [comment]
I think I'll just quickly add tests for the check of smpte formats for now. For [gitlab issue 114](https://git.ebu.io/ebutt/ebutt-part-3/issues/114) tests I will do a new branch and a new PR.

I'll add a comment here as soon as I added the format tests for smpte here.

**Comment by gilbrechbuhler** [comment]
Actually after checking, I think the best is to merge the branch as it is. Indeed if ```ttp:markerMode="continuous"``` is allowed, the XSD as to be modified in consequence (currently it only allows discontinuous), which is out of the scope of this PR. By the way, I was checking tech 3350 (for the definition of dropMode) and realized it does not allow "continuous" as a value for the markerMode, moreover with ```ttp:timeBase="smpte"``` it still says that  ```ttp:markerMode="discontinuous"``` is mandatory.

Anyway, merging this as it is, is the easier method for now as we have multiple things to change for smpte apparently.

**Comment by nigelmegitt** [comment]
Okay, that's fine. The only thing remaining on this is to answer the question:

* [ ] @kozmaz87 to answer query from https://github.com/ebu/ebu-tt-live-toolkit/pull/18#issuecomment-230300247 : is there a way to selectively skip scenario examples that don't work rather than commenting them out?

**Comment by frans-ebu** [comment]
I am happy with this, but admit not having checked in great depth.

**Comment by nigelmegitt** [comment]
I'd like to merge this and raise an issue for skipping invididual scenario example lines that don't work rather than commenting them out. I admit I also have not checked all the tests against the spec, but any missing ones can be added later.

**Comment by nigelmegitt** [comment]
The smpte tests have been moved out of #7 into #52.

The commenting out vs skipping of scenario example lines has been raised as #53.

**Pull request merged**
