### PR TITLE
Replace (broken) Slack invite link with e-mail

### PR DESCRIPTION
**Pull request by frans-ebu**

### CODE REVIEW

**Comment by nigelmegitt** [comment]
Changed base to 2.1.1, so we can make this part of a minor point release. May as well do it "properly"...

**Comment by nigelmegitt** [comment]
I'm not sure why it isn't building though, seems like there's something wrong with the openssl command, maybe the encryption keys need to be refreshed?

**Comment by frans-ebu** [comment]
@nigelmegitt I don't think anything is wrong. This is just a protection against security risks from PRs originating from a forked repository (mine in this case).

See: https://docs.travis-ci.com/user/pull-requests#Pull-Requests-and-Security-Restrictions

So options are:
- Merge anyway
- Create a PR in this git directly

**Comment by nigelmegitt** [comment]
Oh neat! I didn't spot that you did it from a fork. No reason I can think of why not to make the PR in this repository directly. That's what I would have expected to be honest.

**Comment by frans-ebu** [comment]
Does not deploy, as PR comes from a fork (encryption keys, security measure).

**Pull request closed without merging**
