### PR TITLE
#404 remove timing_end_limit

### LINKED ISSUE #404: Typo
There's a typo on line `53:100` of the `...bindings/validation/timing.py`

### PR DESCRIPTION
**Pull request by nigelmegitt**
Fixes #404 by removing `timing_end_limit` key and value from
`TimingValidationMixin._semantic_dataset` since it wasn’t used anywhere.

### CODE REVIEW

**Comment by nigelmegitt** [comment]
Coverage decrease is insignificant.

**Comment by kozmaz87** [comment]
I will look at this today.

**Comment by nigelmegitt** [comment]
Many thanks @kozmaz87 !

**Comment by nigelmegitt** [comment]
Thank you for the review @kozmaz87 - I will merge this.

I searched the code for use of `timing_begin_limit` and found that it is being used at `ebu-tt-live-toolkit/ebu_tt_live/bindings/__init__.py` line 617 and `ebu-tt-live-toolkit/ebu_tt_live/bindings/validation/timing.py` lines 87-91, but nothing seems to depend on it, so it likely is safe (and clean) to remove it.

**Comment by nigelmegitt** [comment]
For cleanliness and symmetry I also removed `timing_begin_limit` in the commit above, fc0b78e, following https://github.com/ebu/ebu-tt-live-toolkit/pull/420#pullrequestreview-35962550 . Will merge without a further review assuming the CI builds pass.

**Pull request merged**
