### PR TITLE
Reference clock identifier validation tests

### PR DESCRIPTION
**Pull request by gilbrechbuhler**
Fix issue #38 

```
Allows the reference clock source to be identified. Permitted only when
ttp:timeBase="clock" AND ttp:clockMode="local" OR when
ttp:timeBase="smpte".
```

### CODE REVIEW

**Comment by gilbrechbuhler** [comment]
DO NOT MERGE BEFORE #57 please, and wait on update from me before merging, I'll have to modify it, I should not have open it before #57 was merged, but it is done so....

**Comment by frans-ebu** [comment]
Looks OK to merge.

**Comment by gilbrechbuhler** [comment]
I agree to wait on #62 so I can add markerMode="continuous" when timeBase="smpte" is used.

**Comment by kozmaz87** [comment]
Happy camper here.

**Comment by nigelmegitt** [comment]
Note that although we are all happy with this there's a hold on merging it until #62 has been merged.

* [ ] #62 merged

**Comment by nigelmegitt** [comment]
Can we now merge this, since #62 has been merged?

**Comment by gilbrechbuhler** [comment]
Not yet, I'll finalize it tomorrow, I need to merge master in the branch and check it one more time.

**Comment by gilbrechbuhler** [comment]
Checked, merge-able as far as I'm concerned

**Comment by frans-ebu** [comment]
Let's go.

**Comment by nigelmegitt** [comment]
Thanks both, merging imminently...

**Comment by nigelmegitt** [comment]
Thanks Gil!

**Pull request merged**
