### PR TITLE
Skip examples

### PR DESCRIPTION
**Pull request by gilbrechbuhler**
For issue #53

### CODE REVIEW

**Comment by gilbrechbuhler** [comment]
We simply group at the end the examples that cannot pass and "skip" them. However they do not appear in the "skipped" count.

**Comment by nigelmegitt** [comment]
Does the skip count normally include a count of every row in the example table in the scenario, or just count each skipped scenario? If it's per-scenario then it's going to be difficult to get this to work 'perfectly'.

**Comment by gilbrechbuhler** [comment]
Normally, when we use @skip on a scenario each row is counted. Here when we skip just some lines they are not counted, I bet it comes from the way pytest parses the tables

**Comment by nigelmegitt** [comment]
Yes, seems like a problem with pytest. I suggest we use the closest we can to a sensible format, i.e. putting `@skip` part way down the list of examples, and raise an issue with pytest.

**Comment by gilbrechbuhler** [comment]
Agreed. However I'm not sure the issue is specific to pytest, I searched for means of commenting scenario examples in other bdd framework and I did not find anything interesting sadly.

**Comment by nigelmegitt** [comment]
Ok, maybe it's a cucumber/gherkin problem then - either way it seems like something we should escalate to wherever it needs to go!

**Comment by gilbrechbuhler** [comment]
Merge-able for me, no conflict.

**Comment by frans-ebu** [comment]
Let's merge :)

**Comment by nigelmegitt** [comment]
There seems to be consensus to merge this: doing so.

**Pull request merged**
