### PR TITLE
utc clock

### PR DESCRIPTION
**Pull request by gilbrechbuhler**
Doing #184 I realised making an UTC clock was really easy in python, so here it is.

### CODE REVIEW

**Comment by nigelmegitt** [comment]
Looks good, I'm confused by the coverage decrease though - does the test not run?

**Comment by gilbrechbuhler** [comment]
It runs but only covers the instanciation, it does not cover the `get_real_clock_time` method. I don't really now if this one is testable as it would be like testing pythons `utcnow()` method. However I just thought about one test I can add, will do that right now.

**Comment by nigelmegitt** [comment]
Looks good to me!

**Comment by nigelmegitt** [comment]
Merging, should facilitate #184

**Pull request merged**
