### PR TITLE
Issue 51 conformance requirements

### PR DESCRIPTION
**Pull request by nigelmegitt**
Fix issue #51 by adding a conformance requirements list markdown document. Needs tests to be added to the right hand column, and also possibly conformance requirements referenced by Tech3370.

### CODE REVIEW

**Comment by frans-ebu** [comment]
Looking good!

I have added one proposal in 0b53ac4 : to make section references explicit, so rows can be read in isolation (may be handy for future auto-ref listing, as well).

**Comment by gilbrechbuhler** [comment]
Great, I'll think of way of referencing the tests in a readable and understandable way.

**Comment by nigelmegitt** [comment]
Thanks @frans-ebu I wondered about that, happy to go with the ref-on-every-line approach.

**Comment by gilbrechbuhler** [comment]
I think the easiest way to reference the tests is to give the path to the file containing the test (feature file in case of bdd) from the root of the project. If you have better ideas :)

**Comment by nigelmegitt** [comment]
What about the scenarios within the feature file?

**Comment by gilbrechbuhler** [comment]
Yes for feature file that might be a great idea. However, I suspect some of the tests for conformance requirements may belong in unit tests, in that case we could just put the test file path's ?

**Comment by gilbrechbuhler** [comment]
Looking at the file, a question came to me :
`Every distinct document with the same sequence identifier shall have a different sequence number.`

How do we plan on enforcing these kind of statements ? I mean, either we keep a list of each sequence going through each node and check on every node, or we simply guarantee that the producers we provide never break this rule and test them ?

I ask because the first solution seems to not be the right one (big performance problems could come from this I think). But in the case on the second one, if someone creates its own producer, we cannot really enforce that, we can only enforce it in our code, the consequence if this error is made will be that the consumer will not have the expected behaviour.

So how should this kind of statements be tested ? Should I just test our producers to be sure that they do not break the rule for example ?

**Comment by nigelmegitt** [comment]
It's a semantic validation test - if you receive a document with a sequence number that's been seen before, and the purpose of the script is to validate the whole sequence, then you have to check that the _n_ documents with the same sequence number are identical. We're testing conformance here, not trying to be performant.

**Comment by gilbrechbuhler** [comment]
Ok so testing this means testing the code/node that performs semantic validation in that case, right ?

For perfomances, I thought validating this on every node, but if it is only on a node that performs semantic validation, this is not an issue indeed.

**Comment by nigelmegitt** [comment]
Yes, I think that's right.

**Comment by gilbrechbuhler** [comment]
May I complete the file in this PR ? Some tests already exist.

**Comment by nigelmegitt** [comment]
Yes, sure. I'm not sure what you're going to add?

**Comment by nigelmegitt** [comment]
Should we be extra clear and change the Tests column header to be "Scenario name"?

**Comment by gilbrechbuhler** [comment]
I think it is a good idea, for now we only reference scenarios, if that changes one day we can always update the column name.

**Comment by nigelmegitt** [comment]
Ok, agreed. Please could you make that tweak too?

**Comment by nigelmegitt** [comment]
Looking good, thanks. Is there something in the test framework that makes scenario names unique, or should we also be including some kind of test path and/or feature name or id?

**Comment by gilbrechbuhler** [comment]
Arf, no, as long as they are not in the same `.feature` files, scenarios can have the same name. Instead of the full path, should I add the `.feature` filename in front of each scenario ?

**Comment by nigelmegitt** [comment]
Yes, `path/to/some.feature` `Scenario`

**Comment by nigelmegitt** [comment]
I think this is looking good. @kozmaz87 does it do enough to answer your question about how we measure how much of the spec we are testing?

**Comment by kozmaz87** [comment]
This is excellent. Happy to go with it.

**Pull request merged**
