### PR TITLE
Bdd/document metadata elements order

### LINKED ISSUE #211: Test R38 and R39

### PR DESCRIPTION
**Pull request by gilbrechbuhler**
Fix #211 

Ensures that the metadata elements introduced in 3370 have to be in the right order and after any other metadata element in documentMetadata.

### CODE REVIEW

**Comment by nigelmegitt** [comment]
Ah, this is useful. Thanks @gilbrechbuhler

**Comment by nigelmegitt** [comment]
This is fine as is, but it would also be useful to include some metadata from tech3350, which is allowed to precede (but not follow) the tech3370 metadata in `documentMetadata`.

**Comment by nigelmegitt** [comment]
That can be a separate PR to test the tech3350 requirement I guess.

**Comment by gilbrechbuhler** [comment]
I did actually with documentIdentifier, but it could be enhanced with more indeed

**Pull request merged**
