### PR TITLE
Availability times in documents

### LINKED ISSUE #102: Add an availability time attribute to `EBUTT3Document` class
For #50

### PR DESCRIPTION
**Pull request by gilbrechbuhler**
fixes #102

### CODE REVIEW

**Comment by nigelmegitt** [comment]
Looks good.

**Comment by kozmaz87** [comment]
This is quite evil from coveralls. It marks the pull request with red cross like CI wouldn't have passed if the coverage decreases...

**Comment by nigelmegitt** [comment]
Not evil - it's keeping us in order! We can still merge anyway, since we can't usefully test this right now.

Do we need to call the setter from the `carriageImpl`s as part of this PR and add tests that they execute properly, or do you want to pick that up elsewhere?

**Comment by gilbrechbuhler** [comment]
Oh indeed I completely forgot to use it in the carriage implementations... I'll add that now. For tests I don't know, the lines I added are basically an attribute along with its getters and setters, I don't know if it needs testing at all. Maybe just checking that an exception is raised when something else than a timedelta is given.

**Comment by nigelmegitt** [comment]
That would do it!

**Comment by kozmaz87** [comment]
yes I believe that it would do. Assuming we don't want to feed it values of string but I guess at that layer of abstraction the canonical timedelta type is a better choice

**Comment by gilbrechbuhler** [comment]
Yes I thought about it when writing the code. We could give a string and the document would then be responsible for converting it to the right timedelta value. But here I thought that it would be better to trust the clock giving the ability time, as this same clock will give us a timedelta respecting the chosen timebase.

**Comment by kozmaz87** [comment]
So you are suggesting in the long run to take out the timedelta conversion from the bindings and put it in the document?

**Comment by gilbrechbuhler** [comment]
No no, not what I meant, I speak only for the availability time here. This is why I think the document should get a timedelta for the availability time and not a string, otherwise we would have to convert the time in the `@availability_time.setter` method and that would be confusing. Because availability time never exists in the xml

**Comment by kozmaz87** [comment]
I agree

**Comment by gilbrechbuhler** [comment]
So I added the test and now the existing carrier of the simple consumer sets the availability time when it receives documents

**Comment by gilbrechbuhler** [comment]
I am going to need this one for the filesystem carriage consumer part :)

**Comment by kozmaz87** [comment]
ACK

**Comment by nigelmegitt** [comment]
Needs conflicts to be resolved.

**Comment by nigelmegitt** [comment]
All looking good. Merging.

**Comment by nigelmegitt** [comment]
(ignoring -0.1% coverage drop)

**Pull request merged**
